# Generated by Django 4.2.7 on 2023-11-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_article_name', models.CharField(help_text='Enter field documentation', max_length=100)),
                ('my_article_index', models.URLField()),
                ('my_article_DOI', models.CharField(max_length=200)),
                ('my_article_title', models.CharField(max_length=200)),
                ('my_article_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['my_article_date'],
            },
        ),
    ]
