# Generated by Django 4.2.7 on 2023-11-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication01', '0002_edu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edu',
            options={'ordering': ['my_edu_index']},
        ),
    ]
