# Generated by Django 4.2.7 on 2023-11-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication01', '0003_alter_edu_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu',
            name='my_edu_date',
            field=models.CharField(default=-4, max_length=30),
            preserve_default=False,
        ),
    ]
