# Generated by Django 4.2.7 on 2023-11-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication01', '0004_edu_my_edu_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_award_name', models.CharField(max_length=100)),
                ('my_award_index', models.CharField(max_length=10)),
                ('my_award_date', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['my_award_index'],
            },
        ),
    ]
