# Generated by Django 4.2.7 on 2023-11-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication01', '0005_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='my_article_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='articles',
            name='my_article_index',
            field=models.CharField(max_length=200),
        ),
    ]
