# Generated by Django 4.2.7 on 2023-11-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication01', '0006_alter_articles_my_article_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['my_articles_date']},
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='my_article_DOI',
            new_name='my_articles_DOI',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='my_article_date',
            new_name='my_articles_date',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='my_article_index',
            new_name='my_articles_index',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='my_article_name',
            new_name='my_articles_name',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='my_article_title',
            new_name='my_articles_title',
        ),
    ]
